# tenants:
#   TENANT_A:
#     mac_vrf_rt_base: 10000
#     pw_rt_base: 1000
#     l1_services:
#       - name: TEN_A_site1_site2_eline
#         type: vpws-pseudowire  # Should be default
#         ids: [ 52, 513 ]
#         nodes: ["PE-01", "PE-04"]
#         interfaces: ["Ethernet5/2.10", "Ethernet5/3.10"]
#     vrfs:
#       TENANT_A_WAN:
#         vrf_rt: 10
#         address_families:
#           - evpn
#         l3_interfaces:
#           - description: "L3vpn service, vlan 100"
#             interfaces: [ Ethernet5/2.100 ]
#             encapsulation_dot1q_vlan: [ 100 ]
#             enabled: true
#             mtu: 9000
#             ip_addresses: [ 10.10.100.2/24 ]
#             nodes: [ PE-01 ]
#           - description: "L3vpn service, vlan 100"
#             interfaces: [ Ethernet5/3.200 ]
#             encapsulation_dot1q_vlan: [ 200 ]
#             enabled: true
#             mtu: 9000
#             ip_addresses: [ 10.10.200.2/24 ]
#             nodes: [ PE-04 ]
#         bgp_peers:
#           10.10.100.1:
#             description: CPE-01
#             remote_as: 65001
#             password: $1c$/ei4LgYRVQVyaE3DDcjbXw==
#             send_community: standard
#             nodes: [ PE-01 ]
#             default_originate:
#               always: true
#           10.10.200.1:
#             description: CPE-02
#             remote_as: 65005
#             password: $1c$/ei4LgYRVQVyaE3DDcjbXw==
#             send_community: standard
#             nodes: [ PE-04 ]
#             default_originate:
#               always: true

