---

# Backone Interfaces

backbone_interfaces:
  p2p_links_ip_pools:
    underlay_pool: 100.64.48.0/24
  p2p_links_profiles:
    default_bb_profile:
      speed: 100full
      mtu: 1500
      isis_hello_padding: false
      isis_metric: 60
      ip_pool: underlay_pool
      isis_circuit_type: level-2
      ipv6_enable: true
  p2p_links:

    # P-01 Links
    - nodes: [ P-01, P-02 ]
      id: 1
      interfaces: [ Ethernet25/1, Ethernet25/1 ]
      profile: default_bb_profile
    - nodes: [ P-01, PE-01 ]
      id: 2
      interfaces: [ Ethernet1/1, Ethernet1/1 ]
      profile: default_bb_profile
    - nodes: [ P-01, PE-02 ]
      id: 3
      interfaces: [ Ethernet2/1, Ethernet50/1 ]
      profile: default_bb_profile
    - nodes: [ P-01, PE-03 ]
      id: 4
      interfaces: [ Ethernet26/1, Ethernet55/1 ]
      profile: default_bb_profile

    # P-02 Links
    - nodes: [ P-02, PE-02 ]
      id: 5
      interfaces: [ Ethernet26/1, Ethernet55/1 ]
      profile: default_bb_profile
    - nodes: [ P-02, PE-03 ]
      id: 6
      interfaces: [ Ethernet4/1, Ethernet50/1 ]
      profile: default_bb_profile
    - nodes: [ P-02, PE-04 ]
      id: 7
      interfaces: [ Ethernet1/1, Ethernet1/1 ]
      profile: default_bb_profile
    - nodes: [ P-02, PE-04 ]
      id: 7
      interfaces: [ Ethernet2/1, Ethernet2/1 ]
      profile: default_bb_profile

    # PE-01 Links
    - nodes: [ PE-01, PE-02 ]
      id: 8
      interfaces: [ Ethernet2/1, Ethernet49/1 ]
      profile: default_bb_profile

