---
# Validation lab
# local users
fabric_name: MPLS_FABRIC

# Sets the administrative subfield of IP/MAC VRF Route-Distinguishers and Route-Targets
# These are actually the defaults. No need to set anything really.
overlay_rd_type:
  admin_subfield: overlay_loopback
overlay_rt_type:
  admin_subfield: 65000

# BGP max-paths and ecmp
bgp_maximum_paths: 4
bgp_ecmp: 4
# evpn_ebgp_multihop: 10

# EVPN prevent readvertising routes
overlay_prevent_readvertise_to_server: true

underlay_routing_protocol: isis
isis_advertise_passive_only: true
# Disabling ISIS hello padding makes it easier with vEOS-lab.
isis_hello_padding: false
isis_ti_lfa:
  enabled: true
  protection: link
  local_convergence_delay: 15000

# What should the defaults be?
isis_default_is_type: level-1-2
isis_default_circuit_type: level-1-2
isis_default_metric: 50

label_distribution:
  # protocol: ldp
  protocol: isis-sr # Should be the default.

# ibgp should be default
overlay_routing_protocol: ibgp
bgp_as: 65000
# If meshing PEs, client-to-client reflection can be turned off using rr bgp defaults.
# bgp_mesh_pes: true

# bgp peer groups passwords
bgp_peer_groups:
  MPLS_OVERLAY_PEERS:
    password: $1c$U4tL2vQP9QwZlxIV1K3/pw==

# Update p2p mtu
p2p_uplinks_mtu: 9000


